### PR TITLE
Delete request must are in_ring package always

### PR DESCRIPTION
**Pull request by nilxam**
Delete reqeut implies a ring type for staging project, according to the staging project design, the delete request can not add to adi staging due to failes to expand the source.

### CODE REVIEW

**Comment by jberry-suse** [comment]
It seems like it might make more sense to simulate the package being in a ring fully by assigning it to one in `supplement()` that way it would be filterable/groupable as such with other options.

**Comment by nilxam** [comment]
whether the delete request is ring package or non-ring package, it must to go through normal staging, so we should avoiding show it as pending request for adi staging ie. Not in a ring:... also adi cmd should not process them.

I just provide a quick fix here otherwise I can run staging adi for TW, if you have a good idea in mind to fix it will be welcomed :)

**Comment by jberry-suse** [comment]
Yeah, I understand. I'll go ahead and try making the change in supplement.

**Comment by nilxam** [comment]
https://github.com/openSUSE/osc-plugin-factory/pull/676 instead

**Pull request closed without merging**
