### PR TITLE
Rely on server-side issue tag check

### PR DESCRIPTION
**Pull request by krig**
I think this should fix the problem. It grabs the first diff of a file ending in .changes in the submit diff.

I haven't fixed the tests, so the tests are failing since it now tries to get the server diff.

Fixes: #358

### CODE REVIEW

**Comment by krig** [comment]
Hmm, this doesn't seem to return what I expect from the public OBS:

https://api.opensuse.org/source/openSUSE:Factory/nano?opackage=nano&oproject=editors&cmd=diff&onlyissues=1&orev=25&view=xml

Gives me

```
<directory name="nano" rev="38" vrev="1" srcmd5="fc6b5b47f112848a1eb6fb8660b7800b">
  <entry name="nano-2.4.1.tar.gz" md5="1c612b478f976abf8ef926480c7a3684" size="1890805" mtime="1429179243" />
  <entry name="nano-2.4.1.tar.gz.asc" md5="a5b725ee67cef5595f7327a84fc80d54" size="181" mtime="1429179243" />
  <entry name="nano.changes" md5="759a3cfc6513ce1c68c61c9c82fdbb72" size="24363" mtime="1429179243" />
  <entry name="nano.keyring" md5="284e50e7b4d0b494dcc7111b704980ec" size="1548" mtime="1427233842" />
  <entry name="nano.spec" md5="3cbbe5d98eee721d3a1aa02d8d23dd00" size="2989" mtime="1429179243" />
</directory>
```

**Comment by krig** [comment]
Ah, or maybe I have to use POST, not GET.

**Comment by coolo** [comment]
yeah, all cmd= are POST

**Comment by krig** [comment]
OK, so I think the code is fine now. However, this breaks all of the tests since the method for checking issues moves to the server... I guess just throwing all the tests away and writing new ones is what is needed :(

**Pull request merged**
