### PR TITLE
osclib/stagingapi: create_adi_project(): use :Staging passthru project.

### LINKED ISSUE #1102: repo-checker no longer blocks invalid licenses
The old repo-checker inspected rpmlint.log and did not let packages pass with an invalid license.

The main issue here is that rpmlint-Factory-strict is not enabled across OBS - as it is too annoying in devel projects and even worse in 3rd party repos... so the invalid licenses are flagged as warnings there only

In adi stagings, this is also not enabled (as it builds against openSUSE:Factory/standard - just like any other 3rd party prj would) - 'proper' staigngs are fine, as they build against openSUSE:Factory:Staging/standard, where the strict filter is injected unconditionally

We need to either find a setup that works for adi to get Factory-strict enabled or have repo-checker kick this out again, as in the past.

### PR DESCRIPTION
**Pull request by jberry-suse**
This allows for project configuration to be injected.

Fixes #1102.

### CODE REVIEW

**Comment by jberry-suse** [comment]
Update to point at just `:Staging`.

**Comment by jberry-suse** [comment]
Updated to include both `:Staging` and `openSUSE:Factory` in path.

**Comment by DimStar77** [comment]
Generally should be fine - the commit message does not really represent what is changed though anymore imho

**Comment by jberry-suse** [comment]
I updated it, not sure when you looked:

```
osclib/stagingapi: create_adi_project(): add :Staging passthru project.
This allows for project configuration to be injected.
```

That seem clear or not?

**Comment by DimStar77** [comment]
yes - that seems fine... must have had a stale screen here

**Pull request merged**
