### PR TITLE
Abichecker

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by aplanas** [comment]
Uhmm bad rebase?

**Comment by lnussel** [comment]
no, it's actually that many commits :)

**Comment by aplanas** [comment]
But https://github.com/openSUSE/osc-plugin-factory/pull/356/files#diff-757c4a9666c97c682e4d40a07a82cc3fR29 is in master:

https://github.com/openSUSE/osc-plugin-factory/blob/master/osclib/memoize.py#L28

**Comment by lnussel** [comment]
yeah, I already cherry picked some commit and submitted them separately

**Pull request merged**
