### PR TITLE
repo_checker: store and compare build hash to skip more aggressively (similar check for project_only)

### LINKED ISSUE #973: repo_checker: speed up reviews by comparing has of staging project psuedometa
Building atop the new `repo_checker` provided in #964 it makes sense to keep a cache of hashes of each staging project pseudometa + `overall_state` from dashboard API and if nothing changed since last review do not bother performing an installcheck or cycle check again.

Since the `repo_checker` runs in a loop it will see non-acceptable, but not declined reviews over and over until the problem is resolved. This was the same with the previous code and even worse since it would look at non-staged requests which means the window for looping was larger.

### LINKED ISSUE #1029: repo_checker: project_only check for full build completed
The previous script just ran with whatever state the repo was in, as does #1028, but it likely makes sense to either wait for build to complete, or perhaps run against the snapshot repo if that is simple enough. That way false-positives due to incomplete rebuild are not included.

This is somewhat tricky in that the check either needs to be run repeatedly to find the right time when everything has settled or needs to be triggered along with other snapshot related bits.

### PR DESCRIPTION
**Pull request by jberry-suse**
- 95777e194f420d1a829af75ff11a3b3d0ed160cc:
    repo_checker: project_only place dashboard update behind dryrun check.

- b8d81e15f6540d63217ff8b8a8dccfb88b8daa4c:
    repo_checker: project_only ensure project repository is published.

- 9b7d12142c198a1075b6d3b858530eb9e6b6c085:
    repo_checker: store and compare build hash to skip more aggressively.

Fixes #973.
Fixes #1029.

### CODE REVIEW

**Comment by jberry-suse** [comment]
`packagelists` is rather under-powered for this bot and the addition of `Leap:15.0` does not help. Effectively should skip re-reviewing stagings until their build changes. This should also allow the `project_only` mode to run without producing false-negatives during rebuilds. As such I will go ahead and enable it.

**Comment by jberry-suse** [comment]
The down-side of this is that if the whitelist is updated repo-checker will not recheck the staging.

**Comment by DimStar77** [comment]
For adi, there might also be changes in oS:F directly that alter the outcome of the check (think install deps were missing, then accepted through a different adi staging). The fact that setting confug won't be cinsidered for change/rescan is kinda a bummer

**Comment by jberry-suse** [comment]
This caches all relevant repos so it would detect that change. Basically all the repos it downloads to check it includes in the hash. If anything I just need to add config hash.

**Comment by jberry-suse** [comment]
Cleaned up code a tad so it can cache more, and included staging project meta revision in hash to detect config changes.

**Comment by jberry-suse** [comment]
For reference the last `repo-checker` run on `packageslists`:

- Oct 31 18:24:18
- Oct 31 23:39:33

Over 5 hours. I would expect this to drop that by 80% at least.

**Pull request merged**
