### PR TITLE
Use python logging in ToTest manager

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by aplanas** [comment]
You do not need to pass the logger to different objects. You can configure the root logger in the main function, and recover it in each module:

```python
# This is my entry point
import logging

# Configure the logger
logging.basicConfig(filename='totest.log', level=logging.DEBUG)
```
You can use that in this way:
```python
import logging

# Get the root logger
LOG = logging.getLogger()
...
LOG.debug('Something something')
# This also works:
logging.info('Something something')
```

More info: https://docs.python.org/2/howto/logging.html#logging-basic-tutorial

**Comment by lnussel** [comment]
@aplanas how can the last commit affect _invalidate_all() which comes from memoize?

**Comment by lnussel** [comment]
ah, it only gets added once a memoize method is called at least once

**Comment by aplanas** [comment]
@lnussel yep, is the wrong thing about monkey patching. Now I am not sure if I need to fix the tearDown method in the test or use a different approach for your last commit.

**Pull request merged**
