### PR TITLE
Disable debuginfo repo

### PR DESCRIPTION
**Pull request by nilxam**

### CODE REVIEW

**Comment by coolo** [comment]
I don't think this is clever. At least perl behaves different when it's compiled without debug

**Comment by nilxam** [comment]
@lnussel want it. do you have more details of the risk?

**Comment by coolo** [comment]
@lnussel wanting it is quite a bad reasoning in itself :)

**Comment by lnussel** [comment]
the test in ring2 with disabled debuginfo didn't help much :(

**Pull request closed without merging**
