### PR TITLE
Return None if has not action/source

### PR DESCRIPTION
**Pull request by nilxam**
eg. DELETE REQUEST

### CODE REVIEW

**Comment by lnussel** [comment]
needs to look for action/target anyways. the source package name could be different

**Comment by nilxam** [comment]
the problem here is about has not action/source entry...

**Comment by nilxam** [comment]
and this is inside of devel_project_get()

**Comment by jberry-suse** [comment]
This was fixed in #662 and should be reverted.

**Comment by jberry-suse** [comment]
Looks like it was already reverted when other change was merged (assume @lnussel changed my PR or somesuch).

**Comment by nilxam** [comment]
yeah, we aware of https://github.com/openSUSE/osc-plugin-factory/pull/662 after merged this change.

**Pull request merged**
