### PR TITLE
pkglistgen: solv_cache_update(): support update repo and 4 way merge (and merge skipping)

### LINKED ISSUE #1396: pkglistgen: use update repo also for drop list generator
There are some python version updates in the update repos that end up having the same version in 42 as in 15. Due to the lp150 release prefix the 42 version is considered newer. Right now the droplist generator only looks at the GA repo where those python modules have a lower version still match the obsoletes tag of the corresponding packages in 15, so doesn't list them in obsoletepackages.inc.

### PR DESCRIPTION
**Pull request by jberry-suse**
- 21961daf8a96f8411caa437201584e67f71bb75f:
    **pkglistgen: solv_cache_update(): support update repo and 4 way merge.**

- 460ab740d99b9a55f296a2b19c9af1be5a346312:
    pkglistgen: do_dump_solv(): support update repos.
    
    Always pull down update repo and only overwrite if changed. Could rework
    more extensively to name based on hash of repomd.xml or somesuch, but would
    likely also want to remove old versions.

- 84b142c00c321cb663c2cbba1809f46857fb867a:
    pkglistgen: solv_merge(): allow array of solv files to merge.

- df4e23c22df2ef6906a7965f707e917ba373f9ba:
    pkglistgen: solv_merge(): skip when inputs are older than merged.

- a11192affd5ec34dacf082cf2dfda06def962c41:
    osclib/conf: leap: set download-baseurl-update.

Fixes #1396.

### CODE REVIEW

**Comment by jberry-suse** [comment]
Need to verify the end result is desired (perhaps via update tests?). It runs properly (completing a full run now for Leap).

**Comment by jberry-suse** [comment]
Inner diff, after refactoring for realizing `mergesolv` support more than 2 files so can avoid `reduce()` to turn three steps into one.

```diff
diff --git a/pkglistgen.py b/pkglistgen.py
index df8bd0d..123491e 100755
--- a/pkglistgen.py
+++ b/pkglistgen.py
@@ -782,25 +782,20 @@ class CommandLineInterface(ToolBase.CommandLineInterface):
 
                 solv_file_nonfree = os.path.join(
                     CACHEDIR, 'repo-{}-{}-{}.solv'.format(nonfree, repo, arch))
-                self.solv_merge(solv_file, solv_file_nonfree, solv_file_merged)
+                self.solv_merge(solv_file_merged, solv_file, solv_file_nonfree)
 
-    def solv_merge(self, solv1, solv2, solv_merged=None):
-        if not solv_merged:
-            # Determine name when called by reduce().
-            if '.merged.' not in solv1:
-                solv_merged = solv1.replace('.solv', '.merged.solv')
-            else:
-                solv_merged = solv1
+    def solv_merge(self, solv_merged, *solvs):
+        solvs = list(solvs) # From tuple.
 
         if os.path.exists(solv_merged):
-            modified = map(os.path.getmtime, [solv1, solv2, solv_merged])
-            if max(modified) <= modified[2]:
+            modified = map(os.path.getmtime, [solv_merged] + solvs)
+            if max(modified) <= modified[0]:
                 # The two inputs were modified before or at the same as merged.
                 logger.debug('merge skipped for {}'.format(solv_merged))
                 return solv_merged
 
         with open(solv_merged, 'w') as handle:
-            p = subprocess.Popen(['mergesolv', solv1, solv2], stdout=handle)
+            p = subprocess.Popen(['mergesolv'] + solvs, stdout=handle)
             p.communicate()
 
         if p.returncode:
@@ -930,7 +925,9 @@ class CommandLineInterface(ToolBase.CommandLineInterface):
 
         if name is not None:
             # Only update file if overwrite or different.
+            ofh.flush() # Ensure entirely written before comparing.
             if not opts.overwrite and os.path.exists(name) and filecmp.cmp(name + '.new', name, shallow=False):
+                logger.debug('file identical, skip dumping')
                 os.remove(name + '.new')
             else:
                 os.rename(name + '.new', name)
@@ -1297,10 +1294,10 @@ class CommandLineInterface(ToolBase.CommandLineInterface):
                 continue
 
             # Merge nonfree solv with free solv or copy free solv as merged.
+            merged = names[0].replace('.solv', '.merged.solv')
             if len(names) >= 2:
-                merged = reduce(self.solv_merge, names)
+                self.solv_merge(merged, *names)
             else:
-                merged = names[0].replace('.solv', '.merged.solv')
                 shutil.copyfile(names[0], merged)
             prior.add(merged)
 
```

**Comment by jberry-suse** [comment]
Also needed a buffer flush to be able to compare files.

**Comment by lnussel** [comment]
python-PyYAML for example was updated in 42.3 to the same version as we have in Leap 15

**Comment by jberry-suse** [comment]
I see the following addition in diff:

```
<obsoletepackage>python-PyYAML</obsoletepackage>
```

**Comment by jberry-suse** [comment]
Deployed https://build.opensuse.org/package/rdiff/openSUSE:Leap:15.0/000product?linkrev=base&rev=141

**Pull request merged**
