### PR TITLE
request_splitter: implement autoselect: False

### PR DESCRIPTION
**Pull request by lnussel**
allow to exempt stagings from automatic selects bases on strategies
by putting autoselect: False in pseudometa

### CODE REVIEW

**Comment by nilxam** [comment]
you can configure it by `splitter-whitelist`  in dashboard/config, or it does not work?

**Comment by jberry-suse** [comment]
Unless intended to be a temporary marking the psuedometa is wiped everytime a staging is emptied or accepted. The current approach it to remove `splitter_info` if no longer want followups. I that's the desire to disable follow-ups without removing strategy info could add a `merge: False` option as that would be more applicable.

Otherwise, the other code that clears psuedometa would need to be changed to make an exception for this. If permanent I would suggest the config like Factory uses.

**Comment by lnussel** [comment]
I was just wondering how to deal with Staging:X in Leap. It's not meant to get any requests.

**Comment by DimStar77** [comment]
For TW we have this in 'config':

> splitter-whitelist = B C D E F G H I J

We want to have manual control over A (at least one ring0 for us) and the project K, L and M (and the two new N and O are also not to be touched by the bot)

**Comment by lnussel** [comment]
ok, I'll try that one then. thanks!

**Pull request closed without merging**
