### PR TITLE
pkglistgen: do_update_and_solve(): check for existence of :DVD instead of rings and pkglistgen-product-family-last config option.

### PR DESCRIPTION
**Pull request by jberry-suse**
First fix towards #1392. I will likely update, but just published to start collecting any fixes needed.

### CODE REVIEW

**Comment by coolo** [comment]
I had to patch some more, but now I run into a problem I don't understand:
```
-> solv_cache_update
Traceback (most recent call last):
  File "./osc-plugin-factory/pkglistgen.py", line 1331, in <module>
    sys.exit(app.main())
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 257, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 280, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 412, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 1100, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "./osc-plugin-factory/pkglistgen.py", line 1038, in do_update_and_solve
    self.update_and_solve_target(apiurl, target_project, target_config, main_repo, opts, drop_list=True)
  File "./osc-plugin-factory/pkglistgen.py", line 1176, in update_and_solve_target
    apiurl, cache_dir_solv, target_project, family_include, opts)
  File "./osc-plugin-factory/pkglistgen.py", line 1220, in solv_cache_update
    project_family = project_list_family_prior(apiurl, target_project, include_self=True)
  File "/home/leaper/osc-plugin-factory/osclib/util.py", line 33, in project_list_family_prior
    for entry in sorted(projects, key=project_list_family_sorter, reverse=True):
  File "/home/leaper/osc-plugin-factory/osclib/util.py", line 46, in project_list_family_sorter
    version = project_version(project)
  File "/home/leaper/osc-plugin-factory/osclib/util.py", line 72, in project_version
    version = float(parts[1])
IndexError: list index out of range
```

**Comment by coolo** [comment]
my other patches:
```
@@ -1129,6 +1130,7 @@ class CommandLineInterface(ToolBase.CommandLineInterface):
         self.copy_directory_contents(group_dir, product_dir,
                                      ['supportstatus.txt', 'groups.yml', 'package-groups.changes'])
         self.change_extension(product_dir, '.spec.in', '.spec')
+        self.change_extension(product_dir, '.product.in', '.product')
 
         self.options.input_dir = group_dir
         self.options.output_dir = product_dir
@@ -1298,7 +1300,7 @@ class CommandLineInterface(ToolBase.CommandLineInterface):
 
     def multibuild_from_glob(self, destination, pathname):
         root = ET.Element('multibuild')
-        for name in glob.glob(os.path.join(destination, pathname)):
+        for name in sorted(glob.glob(os.path.join(destination, pathname))):
             package = ET.SubElement(root, 'package')
             package.text = os.path.splitext(os.path.basename(name))[0]
```

Next to that I need a configurable PRODUCT_SERVICE (ENV will do) and I need to strip DEBUGMEDIUM and SOURCEMEDIUM out of staging scope (in staging projects bootstrap_copy and standard have conflicting versions of glibc, which confuses the collection of debuginfos)

**Comment by coolo** [comment]
Oh, and I'm missing a way to limit scope staging to one of them

**Comment by coolo** [comment]
```
@@ -1195,6 +1197,8 @@ class CommandLineInterface(ToolBase.CommandLineInterface):
 
         delete_kiwis = target_config.get('pkglistgen-delete-kiwis-{}'.format(opts.scope), '').split(' ')
         self.unlink_list(product_dir, delete_kiwis)
+        if opts.scope == 'staging':
+            self.strip_medium_from_staging(product_dir)
 
         spec_files = glob.glob(os.path.join(product_dir, '*.spec'))
         if skip_release:
@@ -1260,6 +1264,16 @@ class CommandLineInterface(ToolBase.CommandLineInterface):
 
         return prior
 
+    # staging projects don't need source and debug medium - and the glibc source
+    # rpm conflicts between standard and bootstrap_copy repository causing the
+    # product builder to fail
+    def strip_medium_from_staging(self, path):
+        medium = re.compile('name="(DEBUG|SOURCE)MEDIUM"')
+        for name in glob.glob(os.path.join(path, '*.kiwi')):
+            lines = open(name).readlines()
+            lines = [l for l in lines if not medium.search(l)]
+            open(name, 'w').writelines(lines)
+
     def move_list(self, file_list, destination):
         for name in file_list:
             os.rename(name, os.path.join(destination, os.path.basename(name)))

```

**Comment by jberry-suse** [comment]
The changes you posted should go in your own PR since they are yours and SLE specific.

Apparently the SLE project names on OBS are not the same as the names on IBS...as that makes sense on some planet. I've updated my project family code to use the IBS names (will need to be reconciled if using for leaper, but best this way). If the drop list is to not be used for SLE then probably want a config option to completely avoid those code blocks rather than stop when `download-baseurl` (for published versions) is not found.

**Comment by jberry-suse** [comment]
`OBS: SUSE:SLE-11:SP1`
`IBS: SUSE:SLE-11-SP1:GA`

To a mere mortal this appears insane.

**Comment by jberry-suse** [comment]
I expect this to conclude my code changes towards #1392 as the rest pertain to #1329.

**Comment by coolo** [comment]
sle11 predates leap and the obs projects were merely dumping grounds. I think SLE11 was even moved in IBS when moving to obs maintenance.

**Pull request merged**
