### PR TITLE
Add devel:openQA:tested to whitelist for auto-submit

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by nilxam** [comment]
you really want to use a project name has "testing" included to be a valid devel project? :)

**Comment by okurz** [comment]
yes, because it should be more stable than "devel:openQA" itself. packages are copied to "testing", tested in openQA-in-openQA tests, then submitted

**Comment by okurz** [comment]
also, Dimstar agreed with the name :-)

**Comment by okurz** [comment]
'testing' -> 'tested', as discussed in jangouts call

**Pull request merged**
