### PR TITLE
osc-staging: implement colorization using colorama for adi and list, along with some formatting cleanups.

### PR DESCRIPTION
**Pull request by jberry-suse**
Something I was playing around with as it drastically improves the ability to scan/read the output which is relatively busy. Can try and make colorama not required by mocking it and falling back to simple mock when not available.

Try it out and see if it is helpful.

### CODE REVIEW

**Comment by jberry-suse** [comment]
Example, but obviously the color scheme will likely be different based on your terminal setup.

image
image

**Comment by DimStar77** [comment]
Played around with this locally and the coloring looks reasonable here (and it's easy switched off if not wanted)

👍 from me

**Comment by jberry-suse** [comment]
Refactored a bit to add color everywhere in `adi` and some formatting cleanups while in there. @DimStar77 seemed to agree the sr# prefix was more annoying that useful in the context due to being included in copy/paste when double click to select. Also added `staging.color` option to `~/.oscrc` which allows the colors to be disable outright.

**Comment by jberry-suse** [comment]
Key `adi` text changes are:

- `review:` instead of `missing reviews for` (which provides consistent status column
- `ready:` instead of `is ready` in some cases while others had `ready:`

**Pull request merged**
