### PR TITLE
Don't freeze bash-completion-AGGR

### PR DESCRIPTION
**Pull request by nilxam**
Should not freeze aggregate pacakge in the staging, thus do not freeze bash-completion-AGGR as well. ie. it should not have the build result in the staging project.

### CODE REVIEW

**Comment by lnussel** [comment]
so we have a build loop with bash-completion or what is bash-completion-AGGR for? can we break the loop?

**Comment by nilxam** [comment]
bash-completion has been in ring0 but now it was in ring1, in my memory I only recall it is an compromise deal, ie. some stuff runtime requires bash-completion in ring0 however bash-completion changed its build-deps and that change is expensive for ring0 itself.

**Comment by nilxam** [comment]
but bash-completion has build-deps change afterward, should worth to check can we move it back to ring0 instead of aggreegate pkgs.

**Comment by DimStar77** [comment]
I think this is obsolete - I could successfully remove bash-completion-AGGR from ring0 without anything really caring for it

**Comment by coolo** [comment]
there was a bootstrap problem at one point with an util-linux update. This came from SP1 update

**Pull request closed without merging**
