### PR TITLE
TW Staging media: Add Mesa-demo to Staging2 DVD for openQA test

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Comment by DimStar77** [comment]
This is a requirement for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/4443

The same/similar change should also be done for Leap (@lnussel @nilxam )

**Comment by DimStar77** [comment]
(this diff is currently already live on pkglist vm)

**Comment by nilxam** [comment]
LGTM

**Comment by nilxam** [comment]
https://build.opensuse.org/package/rdiff/openSUSE:Leap:15.0:Rings:2-TestDVD/000package-groups?linkrev=base&rev=7 should be something we needed for Leap ring2.

**Pull request merged**
