### PR TITLE
Exclude repos with missing deps as goodrepos.

### PR DESCRIPTION
**Pull request by aplanas**
A good repo now needs to be compiled and also no missing packages.

### CODE REVIEW

**Comment by aplanas** [comment]
Under review in packagelists.

**Comment by nilxam** [comment]
if this already deployed on packagelists, then I wonder "ERROR -- An exception happends while checking a group [list index out of range]" message is related or not...

**Comment by aplanas** [comment]
For some reason I didn't receive a github email to this comment.  I amended the commit, changing the order when the test cycle is done.  Now there is the possibility that goodrepos become empty.

**Comment by aplanas** [comment]
Do not merge this. Is completely crap.

**Comment by coolo** [comment]
someone had to say it :)

**Pull request closed without merging**
