### PR TITLE
Make number of expected jobs architecture specific

### PR DESCRIPTION
**Pull request by k0da**
90 is too high number of expected jobs for PowerPC.

Signed-off-by: Dinar Valeev <dvaleev@suse.com>

### CODE REVIEW

**Comment by k0da** [comment]
@aplanas The change works for me.

**Comment by aplanas** [comment]
@k0da I know why it works for you, but still is wrong: ToTest132, or any new class that derives from ToTestBase will not overwrite `jobs_num` and will use the one in the base class, that is returning a random string instead of a number.

So please:
* return a good estimation in the base class (5, 10? IDK)
* or raise an exception in the base class and provide some value in the overwritten version of every ToTestBase class (missing ToTest132 that sometime in the future will be renamed)

**Comment by coolo** [comment]
^what aplanas said

**Comment by k0da** [comment]
updated. jobs_num is set to 90 globally and overrided only for Factory:PowerPC project

**Comment by aplanas** [comment]
Thanks! : )

**Pull request merged**
