### PR TITLE
ReviewBot: make interval work without tty

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by lnussel** [comment]
so @bugfinder doesn't have to use screen :)

**Comment by coolo** [comment]
poor Rudi!

**Comment by jberry-suse** [comment]
Still not sure why using screen instead of systemd + journal as is supported by this repo.

**Comment by coolo** [comment]
because of the check that lnussel just patched out? And Rudi doesn't want systemd timers so he can implement a monitor check if the service is running - so prefers the interval check... that didn't work without screen until this PR

**Comment by jberry-suse** [comment]
IT worked out something for such services on packagelists that use timers since you really only care if it ever exited with failure, but seems like it go a bit messed up when lnussel changed the service type as I get more emails.

**Pull request merged**
