### PR TITLE
given the correct ring_dvd path

### PR DESCRIPTION
**Pull request by nilxam**
looks like self.crings is indicating the correct path of rings dvd prj, self.project is "openSUSE:Factory" I think

### CODE REVIEW

**Comment by DimStar77** [comment]
I was first with that :package: 
https://github.com/DimStar77/osc-plugin-factory/commit/3dcdb9709f617f6ec4a5bd0db90d92e14189a022

**Comment by nilxam** [comment]
aha, https://github.com/openSUSE/osc-plugin-factory/pull/301 had 2 commits included, sorry for  I was missed that :P

let's closing

**Comment by nilxam** [comment]
after discuss with DimStar, reopened this PR then, this PR is shorter and will/can quickly merge than #301

**Comment by nilxam** [comment]
@aplanas if we all agree this is the correct fix(I guess we are :) , could you review and merge this PR? :)

**Comment by aplanas** [comment]
Uau! @DimStar77 good catch.  I introduced this bug here:
https://github.com/aplanas/osc-plugin-factory/commit/c9d1e06ca80f231a87703ec24cbe5c6dd9386ed7#diff-f426bb4d7b189a98f1b6d86f95d7919bR688

**Pull request merged**
