### PR TITLE
Enhance fallback-onfail review mode

### PR DESCRIPTION
**Pull request by sbahling**
- Add message when setting fallback reviewer indicating the
  ReviewBot failure
- Do NOT set review to "accepted". Nothing has been "accepted" yet;
  just delegated to human review.
- Fixed debug output (state should be newstate)

### CODE REVIEW

**Comment by sbahling** [comment]
This is for using fallback-onfail with openSUSE:Backports. Not sure about other users of this review mode, and if these changes would break things for others.

**Comment by DimStar77** [comment]
>Do NOT set review to "accepted". Nothing has been "accepted" yet;
just delegated to human review.

The bot has to accept 'his' review - otherwise the human review means nothing.

**Comment by sbahling** [comment]
> The bot has to accept 'his' review - otherwise the human review means nothing.

OK. In my testing I only had one account (mine) to use for all roles (requester, bot, and fallback reviewer) and in that case it appeared as if the fallback review got automatically accepted. I will try testing with separate users.

**Comment by sbahling** [comment]
OK. After testing under more accurate conditions, I don't need this at all - things work as expected. Closing pull request.

**Pull request closed without merging**
